import os
import sys
import subprocess
import requests
import json
import time

def read_error_log(file_path="build_error.log"):
    if not os.path.exists(file_path):
        print(f"Error log file {file_path} not found.")
        sys.exit(1)
    with open(file_path, "r") as f:
        return f.read()

def call_ai_api(api_key, error_content):
    # This is a hypothetical endpoint since no specific URL was provided.
    # It assumes the API accepts a JSON with the error log and returns a list of diffs.
    # We will pass the necessary prompt to it.
    endpoint = os.environ.get("JULES_API_URL", "https://api.example.com/v1/auto-fix")

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }

    payload = {
        "error_log": error_content,
        "instructions": "Analyze the provided Flutter Android build error log. Provide the necessary code fix as a unified diff patch that can be directly applied using the patch command. Ensure the diff handles file paths correctly."
    }

    print(f"Sending request to AI API at {endpoint}...")
    try:
        response = requests.post(endpoint, headers=headers, json=payload, timeout=60)
        response.raise_for_status()
        data = response.json()
        return data.get("patch", "")
    except Exception as e:
        print(f"Failed to communicate with AI API: {e}")
        sys.exit(1)

def apply_patch(patch_content):
    patch_file = "ai_fix.patch"
    with open(patch_file, "w") as f:
        f.write(patch_content)

    print("Applying patch...")
    result = subprocess.run(["patch", "-p1", "-i", patch_file], capture_output=True, text=True)
    if result.returncode != 0:
        print("Failed to apply patch:")
        print(result.stdout)
        print(result.stderr)
        sys.exit(1)
    print("Patch applied successfully.")

def create_pull_request(branch_name):
    print("Committing changes...")
    subprocess.run(["git", "add", "."], check=True)
    subprocess.run(["git", "commit", "-m", "fix: automated AI resolution for build failure"], check=True)

    print(f"Pushing branch {branch_name}...")
    subprocess.run(["git", "push", "--set-upstream", "origin", branch_name], check=True)

    print("Creating Pull Request...")
    result = subprocess.run([
        "gh", "pr", "create",
        "--title", "fix: Automated AI Build Failure Resolution",
        "--body", "This PR contains an automated fix generated by the AI agent based on the recent build failure logs.",
        "--base", "main"
    ], capture_output=True, text=True)

    if result.returncode == 0:
        print(f"Pull Request created successfully: {result.stdout.strip()}")
    else:
        print(f"Failed to create PR:\n{result.stderr}")
        sys.exit(1)

def main():
    api_key = os.environ.get("JULES_API_KEY")
    if not api_key:
        print("Missing JULES_API_KEY environment variable. Cannot call AI API.")
        sys.exit(1)

    error_content = read_error_log()

    if not error_content.strip():
        print("Error log is empty. Nothing to analyze.")
        sys.exit(0)

    patch_content = call_ai_api(api_key, error_content)

    if not patch_content or not patch_content.strip():
        print("AI API returned an empty patch. No fix could be determined.")
        sys.exit(0)

    branch_name = f"auto-fix/build-failure-{int(time.time())}"
    print(f"Creating new branch {branch_name}...")
    subprocess.run(["git", "checkout", "-b", branch_name], check=True)

    apply_patch(patch_content)

    create_pull_request(branch_name)

if __name__ == "__main__":
    main()
